### ISSUE TITLE
Add lib folder structure to NuGet package

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.LongPath.Module#3]
Currently, the Cake.LongPath.Module NuGet Package places all files into the root of the NuGet package:

![image](https://cloud.githubusercontent.com/assets/1271146/19928653/446db2f2-a0f7-11e6-80e0-1388a9ac1fcc.png)

This needs to be corrected to place them into the appropriate lib folder.  In this case `lib\net45\`

See here: http://docs.nuget.org/ndocs/schema/nuspec#examples

**Comment by devlead** [comment]
Would that work with module resolution though? Will have to test if it scans framework folders under modules. Maybe @patriksvensson knows?

**Comment by gep13** [comment]
@devlead ah, good question!  I was going through the motion of adding this issue to all projects in the cake-contrib organisation.

**Comment by gep13** [comment]
Nice one!

**Comment by patriksvensson** [comment]
@gep13 @devlead I'm not sure to be honest, but we should respect frameworks if we're not doing this today.
