### ISSUE TITLE
Error: Method 'Move' in type 'Cake.LongPath.Module.LongPathDirectory' does not have an implementation.

### ISSUE THREAD

**Issue by nagoh** [cake-contrib/Cake.LongPath.Module#5]
Hi

Getting an issue with this, specifically:

Error: Method 'Move' in type 'Cake.LongPath.Module.LongPathDirectory' from assembly 'Cake.LongPath.Module, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Any help would be much appreciated, I can't see the method that needs implementing?

Regards

**Comment by nagoh** [comment]
Oh- looks like nuget package https://www.nuget.org/packages/Cake.LongPath.Module/0.0.2-alpha hasn't been updated

**Comment by devlead** [comment]
fixed by #8
